### ISSUE TITLE
Problem with Cocoapods on iOS Swift project

### ISSUE THREAD

**Issue by VictoremWinbringer** [TelegramMessenger/TGPassportKit#1]
on "pod install" writes 
`Unable to find a specification for 'TGPassportKit'`
Podfile: 
```
target 'TestTelegramApi' do
  use_frameworks!
pod 'TGPassportKit'
pod 'Alamofire'
end
```

**Comment by laktyushin** [comment]
I guess you have a problem with your Specs Repo. You can try running `pod repo update && pod setup` and then repeat `pod install`.

**Comment by VictoremWinbringer** [comment]
Thank you. That helped
